<?php
/**
 * Default page_content seeds shared by install.php and upgrade.php
 */
return [
    // About
    'about_banner_title' => 'About Our Profile',
    'about_ceo_title' => 'CEO Message',
    'about_ceo_quote' => '"Choosing to study abroad is a life-altering choice. At Naseeb Consultant, we are committed to making this transition secure, transparent, and direct. We treat every student application as our own, counseling you with professional integrity rather than commercial greed. Over the past decade, we have watched thousands of our candidates build stellar careers globally. Your dream is safe in our hands."',
    'about_ceo_name' => 'Muhammad Abdullah',
    'about_ceo_role' => 'Founder & Managing Director, Naseeb Consultant',
    'about_ceo_initials' => 'MD',
    'about_story_subtitle' => 'A Decade of Integrity',
    'about_story_title' => 'Empowering Careers Since 2011',
    'about_story_p1' => 'Naseeb Consultant was established in 2011 with a simple vision: to bridge the gap between talented Pakistani students and prestigious universities in the UK, Turkey, China, Lithuania, Poland, France, Russia, and across Europe. Over the past 15 years, we have grown from a local Lahori counseling center into one of Pakistan\'s most trusted international education agencies.',
    'about_story_p2' => 'We handle admissions portfolios for UK, Turkey, China, Lithuania, Poland, France, Russia, and other European destinations. Our counseling staff ensure that visa filings align perfectly with the latest embassy rules.',
    'about_check1' => 'Officially Registered Agency',
    'about_check2' => 'Certified Career Mentors',
    'about_values_subtitle' => 'Naseeb Consultant Ethics',
    'about_values_title' => 'Our Founding Pillars',
    'about_values_desc' => 'At Naseeb Consultant, we believe that education guidance should be driven by ethics, transparency, and a commitment to academic success.',
    'about_value1_title' => 'Absolute Transparency',
    'about_value1_text' => 'We provide clear, upfront details about tuition fees, university expectations, visa chances, and embassy expenses. No hidden charges or false promises.',
    'about_value2_title' => 'Professional Excellence',
    'about_value2_text' => 'Our counselors undergo continuous training and certification from boards like ICEF to keep visa documents compliant with global guidelines.',
    'about_value3_title' => 'Future-Focused Planning',
    'about_value3_text' => 'We do not just look at admission; we evaluate post-study work permits, PR opportunities, and job market metrics to guide your career path.',
    'about_cred_subtitle' => 'Global Recognition',
    'about_cred_title' => 'Our Professional Credentials',
    'about_cred_desc' => 'We maintain direct registrations and partnerships with the world\'s leading academic bodies, certifying our professionalism.',
    'about_cred1_title' => 'British Council',
    'about_cred1_text' => 'Registered IELTS Training & Registration Node',
    'about_cred2_title' => 'ICEF Certified',
    'about_cred2_text' => 'Trained Agency for International Counselors',
    'about_cred3_title' => 'Campus France',
    'about_cred3_text' => 'Authorized guidance for France & European admissions',
    'about_cred4_title' => 'Pearson PTE',
    'about_cred4_text' => 'Authorized PTE Voucher Discount Partner',

    // Services
    'services_banner_title' => 'Visa Services & Eligibility',
    'services_subtitle' => 'Naseeb Consultant Offerings',
    'services_title' => 'Admissions, Visa, and Training Support',
    'services_desc' => 'We guide you through every stage of foreign education, ensuring high compliance at admissions, documentation translation, and visa interviews.',
    'services_card1_title' => 'Student Visa Processing',
    'services_card1_text' => 'Complete visa file compilation, bank statement validation, and interview prep to keep your application compliant with embassies.',
    'services_card1_b1' => 'Bank Statement Formats',
    'services_card1_b2' => 'Document Legalizations',
    'services_card1_b3' => 'Mock Interview Series',
    'services_card2_title' => 'Language Test Classes',
    'services_card2_text' => 'Join intensive IELTS, PTE Academic, and Duolingo English Test classes. Learn tips from high-scoring trainers in Lahore.',
    'services_card2_b1' => 'IELTS General & Academic',
    'services_card2_b2' => 'PTE Voucher Discounts',
    'services_card2_b3' => 'Weekly Writing Evaluation',
    'services_card3_title' => 'Spouse & Work Visas',
    'services_card3_text' => 'Advisory counseling services for students looking to travel with spouses or graduates seeking Schengen job search permits.',
    'services_card3_b1' => 'Spouse Visa Rights Support',
    'services_card3_b2' => 'Financial Sufficiency Files',
    'services_card3_b3' => 'Schengen Job Search Permits',
    'services_tool_subtitle' => 'Visa Probability Diagnostic',
    'services_tool_title' => 'Interactive Visa Eligibility Tool',
    'services_tool_desc' => 'Provide your current credentials to calculate your probability score for study admissions and visa approvals instantly.',
    'services_tool_sidebar_title' => 'Evaluate Your Profile',
    'services_tool_sidebar_text' => 'Embassy rules vary by country. Our calculator evaluates GPA, English benchmarks, and country requirements to give a clear probability score.',
    'services_tool_feat1_title' => 'Instant Feedback',
    'services_tool_feat1_text' => 'Get customized diagnostic scores in seconds.',
    'services_tool_feat2_title' => 'Embassy Compliant',
    'services_tool_feat2_text' => 'Evaluated using typical UK, Schengen, and destination-specific embassy metrics.',

    // Scholarships
    'scholarships_banner_title' => 'Scholarship Highlights',
    'scholarships_intro_subtitle' => 'Financial Relief',
    'scholarships_intro_title' => 'Scholarships in Our Destinations',
    'scholarships_intro_p1' => 'Studying abroad doesn\'t have to be a heavy burden. We help Pakistani students apply for government and university scholarships in the UK, Turkey, China, Lithuania, Poland, France, Russia, and other European countries.',
    'scholarships_intro_p2' => 'Naseeb Consultant guides you through admission files, financial documentation, scholarship applications, and visa stamping for every destination we serve.',
    'scholarships_tip_title' => 'Key Pro Tip for Turkey',
    'scholarships_tip_text' => 'Türkiye Bursları scholarships can cover tuition, accommodation, health insurance, and flights. Strong applications focus on academics, motivation letters, and complete documentation.',
    'scholarships_image' => 'images/graduation-cermony.jpg',
    'scholarships_list_subtitle' => 'Destination Scholarships',
    'scholarships_list_title' => 'Programs We Cover',
    'scholarships_list_desc' => 'Scholarship support for UK, Turkey, China, Lithuania, Poland, France, Russia, and other European study destinations.',
    'scholarships_prog1_title' => 'Türkiye Bursları',
    'scholarships_prog1_text' => 'Turkey\'s flagship government scholarship covering tuition, accommodation, health insurance, and travel for international students.',
    'scholarships_prog1_b1' => 'Fully Covered Tuition Fees',
    'scholarships_prog1_b2' => 'Monthly Living Stipend',
    'scholarships_prog1_b3' => 'Accommodation & Health Cover',
    'scholarships_prog2_title' => 'China CSC Scholarship',
    'scholarships_prog2_text' => 'Chinese Government Scholarship for undergraduate, master\'s, and PhD programs at top Chinese universities.',
    'scholarships_prog2_b1' => 'Tuition Fee Waiver',
    'scholarships_prog2_b2' => 'Monthly Stipend & Accommodation',
    'scholarships_prog2_b3' => 'Medical Insurance Support',
    'scholarships_steps_title' => 'How to Apply for Naseeb Consultant Scholarships',
    'scholarships_step1_title' => 'Academic Review',
    'scholarships_step1_text' => 'Bring your degrees, transcripts, and language results to Naseeb Consultant Lahore Moon Market office for academic verification.',
    'scholarships_step2_title' => 'Financial Filing',
    'scholarships_step2_text' => 'We compile family income certificates, property details, and bank letters matching scholarship parameters.',
    'scholarships_step3_title' => 'Embassy Stamping',
    'scholarships_step3_text' => 'We submit visa filings to the respective consulates. Visa stamping secures your entrance to campus.',

    // Destinations page helper text
    'destinations_banner_title' => 'Study Destinations',
    'destinations_search_hint' => 'Type to filter through 8+ destinations instantly',
    'destinations_search_placeholder' => 'Search by country, requirements, or intake...',
];
